### ISSUE TITLE
自用在openwrt里的docker有必要使用k8s来管理吗？

### ISSUE THREAD

**Issue by ywgf88** [ykxVK8yL5L/dockertemplates#1]
我看现在docker都是使用k8s来管理，自用的docker有必要搞个k8s吗？同时有必要学习这方面的内容吗？如何可以，大神也出个这方面的视频吧。

**Comment by ykxVK8yL5L** [comment]
不好意思  从未看过issues😅    我自己是在openwrt上使用docker 主要是portainer docker-man做为辅助。 稍后我试下k8s，看有我现在的使用方法方便没。 再次抱歉现在才回复。

**Comment by ykxVK8yL5L** [comment]
> 我看现在docker都是使用k8s来管理，自用的docker有必要搞个k8s吗？同时有必要学习这方面的内容吗？如何可以，大神也出个这方面的视频吧。

**Comment by ykxVK8yL5L** [comment]
> 我看现在docker都是使用k8s来管理，自用的docker有必要搞个k8s吗？同时有必要学习这方面的内容吗？如何可以，大神也出个这方面的视频吧。

抱歉，从未查看issues所以现在才回复😅。我自己是在openwrt上使用。主要是portainer进行日常管理，docker-man备用。稍后我看下k8s，看有没有我现在的方法方便。

**Comment by ykxVK8yL5L** [comment]
> 我看现在docker都是使用k8s来管理，自用的docker有必要搞个k8s吗？同时有必要学习这方面的内容吗？如何可以，大神也出个这方面的视频吧。

大概看了下k8s，个人感觉自用的话没必要用k8s。以我自己为例，一共不到10个容器，运行十分稳定，除了升级镜像外几乎没动过。 当然你要是容器集群的话当我没说。
